services:
  frontend:
    image: ${FRONTEND_IMAGE_NAME}
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    networks:
      - my-network
    environment:
      - NGINX_PORT=${FRONTEND_PORT}
      - NGINX_PROXY=http://${PROJECT_NAME}:${BACKEND_PORT}/api

  backend:
    image: ${BACKEND_IMAGE_NAME}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    networks:
      - my-network
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - my-network
    volumes:
      - keep-data:/data/db

networks:
  my-network:
    driver: bridge

volumes:
  keep-data:
    driver: local
