name: ${PROJECT_NAME}
services:
  pf-frontend:
    image: ${FRONTEND_IMAGE_NAME}
    stdin_open: true
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    networks:
      - ${NETWORK_NAME}
    environment:
      - NGINX_PORT=${FRONTEND_PORT}
      - NGINX_PROXY=http://${PROJECT_NAME}:${BACKEND_PORT}/api
  pf-backend:
    image: ${BACKEND_IMAGE_NAME}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - database
    networks:
      - ${NETWORK_NAME}
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
  database:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - ${NETWORK_NAME}
    volumes:
      - keep-data:/data/db

networks:
  ${NETWORK_NAME}:
    driver: bridge

volumes:
  mongo-data:
    driver: local
