name: ${PROJECT_NAME}
services:
  pf-frontend:
    image: ${FRONTEND_IMAGE_NAME}
    stdin_open: true
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    networks:
      - pf-net
    environment:
      - NGINX_PORT=${FRONTEND_PORT}
      - NGINX_PROXY=http://localhost:5001/api
  pf-backend:
    image: ${BACKEND_IMAGE_NAME}
    ports:
      - 5001:5001
    depends_on:
      - database
    networks:
      - pf-net
    environment:
      - MONGO_URI=mongodb://database:27017/shorterURL
      - JWT_SECRET=${JWT_SECRET}
  database:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - pf-net
    volumes:
      - mongo-data:/data/db

networks:
  pf-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local
