services:
  frontend:
    image: ${FRONTEND_IMAGE_NAME}
    container_name: ${PROJECT_NAME}-frontend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    networks:
      - ${NETWORK_NAME}
    environment:
      - NGINX_PORT=${FRONTEND_PORT}
      - NGINX_PROXY=http://${PROJECT_NAME}-backend:${BACKEND_PORT}/api
      - VITE_SERVER_URL=http://${PROJECT_NAME}-backend:${BACKEND_PORT}/api

  backend:
    image: ${BACKEND_IMAGE_NAME}
    container_name: ${PROJECT_NAME}-backend
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - mongo
    networks:
      - ${NETWORK_NAME}
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}

  mongo:
    image: mongo:latest
    container_name: ${PROJECT_NAME}-db
    ports:
      - 27017:27017
    networks:
      - ${NETWORK_NAME}
    volumes:
      - keep-data:/data/db

networks:
  ${NETWORK_NAME}:
    name: ${NETWORK_NAME}

volumes:
  keep-data:
    name: ${PROJECT_NAME}-data
